### ISSUE TITLE
Broken link to FAQ

### ISSUE THREAD

**Issue by nmartensen** [Debian/debiman#83] opened 2017-06-24 17:01 UTC
Example: At the bottom of https://manpages.debian.org/stretch/dash/sh.1.en.html, the FAQ link points to https://manpages.debian.org/stretch/dash/faq.html, which then says "Manpage not found".

**Comment by stapelberg** [comment] 2017-06-24 17:37
Thanks for the report!

@anarcat Since you introduced this, would you like to fix the link (just needs a preceding slash, I think) and trigger a full re-render please?

**Comment by anarcat** [comment] 2017-06-26 13:30
sure, will do now.

**Comment by anarcat** [comment] 2017-06-26 13:31
job started should be completed in a few hours (and propagated in a day or two?). i notice the 404 doesn't have the FAQ links though... is that normal?

**Comment by anarcat** [comment] 2017-06-26 13:39
the rendering crashed, not sure what happened there, and not much time to diagnose further this week:

```
2017/06/26 13:38:00 getcontents.go:85: getting "experimental/contrib/Contents-ppc64el.gz" (hash dd6c962d4adb01d3239be70adcb19acc38ada4506476e437cef0e874d938894f)
panic: runtime error: index out of range

goroutine 1 [running]:
main.getContents(0xc420398000, 0xc42f4cc027, 0xc, 0x9391f6, 0x7, 0xc43c256c40, 0xe, 0xe, 0xc4251c7aa0, 0x0, ...)
        /home/michael/go/src/github.com/Debian/debiman/cmd/debiman/getcontents.go:145 +0x13b1
main.getAllContents(0xc420398000, 0xc42f4cc027, 0xc, 0xc4201c46e0, 0xc4251c7aa0, 0x0, 0x0, 0x0, 0xf, 0xc439285bc0)
        /home/michael/go/src/github.com/Debian/debiman/cmd/debiman/getcontents.go:195 +0x245
main.buildGlobalView(0xc420398000, 0xc42039a000, 0x7, 0x7, 0x7fff95f5a76c, 0x2a, 0xbe4c6107dddb83d3, 0x1440c89a, 0xcb88a0, 0x0, ...)
        /home/michael/go/src/github.com/Debian/debiman/cmd/debiman/globalview.go:229 +0x3d0
main.logic(0x7fff00000030, 0x988ef8)
        /home/michael/go/src/github.com/Debian/debiman/cmd/debiman/main.go:86 +0x20b
main.main()
        /home/michael/go/src/github.com/Debian/debiman/cmd/debiman/main.go:177 +0x11b
```

**Comment by stapelberg** [comment] 2017-06-26 13:57
Will have a look at the panic later today.

The 404 pages should be updated once the assets repository is pulled and debiman-auxserver is restarted on both manziarly and cgi-grnet-01

**Comment by anarcat** [comment] 2017-06-27 18:07
*prod* i'm a bit worried the interrupted run left things inconsistent... is that a problem?

**Comment by stapelberg** [comment] 2017-06-27 18:11
Files are updated atomically, so there shouldn’t be any detrimental effects from crashes.

**Comment by stapelberg** [comment] 2017-06-27 18:20
I can reproduce this issue locally. Having a closer look now.

**Comment by stapelberg** [comment] 2017-06-27 18:50
Pushed a fix. Full re-render running now.

**Closed** 2017-07-03 19:42 UTC
