### ISSUE TITLE
Paragraph (code?) not indented as in man

### ISSUE THREAD

**Issue by ecksun** [Debian/debiman#32] opened 2017-01-19 00:49 UTC
Looking at [crontab(5)](https://manpages.debian.org/testing/cron/crontab.5.en.html) in my manpage viewer shows code blocks (is what I think they are) being indented, like so:

```
will not work as you might expect. And neither will this work

    A=1
    B=2
    C=$A $B

There will not be any subsitution for the defined variables in the last value.
```

However not on the page, where it is rendered like all other text:

```
...
will not work as you might expect. And neither will this work

A=1
B=2
C=$A $B

There will not be any subsitution for the defined variables in the last value.
```

Browsers:

```
$ firefox -v
Mozilla Firefox 45.6.0
$ chromium --version
Chromium 55.0.2883.75 built on Debian stretch/sid, running on Debian stretch/sid
```

**Comment by stapelberg** [comment] 2017-01-19 07:27
Thanks for the report. Closing this as a duplicate of https://github.com/Debian/debiman/issues/21

**Closed by stapelberg** 2017-01-19 07:27 UTC
